#!/usr/bin/env python3
"""Generate an HTML summary report after the full pipeline finishes."""

import re
import json
import base64
from pathlib import Path
from datetime import datetime

OUTDIR    = Path("results")
PLOT_DIR  = OUTDIR / "plots"
MMPBSA    = OUTDIR / "mmpbsa" / "FINAL_RESULTS_MMPBSA.dat"
REPORT    = OUTDIR / "report.html"


def img_b64(path: Path) -> str:
    if not path.exists():
        return ""
    data = base64.b64encode(path.read_bytes()).decode()
    return f'<img src="data:image/png;base64,{data}" style="max-width:100%">'


def parse_mmpbsa(dat_path: Path) -> dict:
    if not dat_path.exists():
        return {}
    text = dat_path.read_text()
    results = {}
    for m in re.finditer(
        r"(VDWAALS|EEL|EGB|EPB|ESURF|DELTA G binding)\s+=\s+([-\d.]+)\s+\+/-\s+([-\d.]+)",
        text
    ):
        results[m.group(1)] = {"mean": float(m.group(2)), "std": float(m.group(3))}
    return results


def generate_report():
    mmpbsa = parse_mmpbsa(MMPBSA)
    dg = mmpbsa.get("DELTA G binding", {})

    rmsd_img  = img_b64(PLOT_DIR / "rmsd.png")
    dcomp_img = img_b64(PLOT_DIR / "mmpbsa_decomposition.png")

    import yaml
    params = yaml.safe_load(Path("config/params.yaml").read_text())

    html = f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<title>MD Simulation Report</title>
<style>
  body {{ font-family: Arial, sans-serif; max-width: 1000px; margin: 40px auto; color: #333; }}
  h1   {{ color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 8px; }}
  h2   {{ color: #2980b9; margin-top: 30px; }}
  .card {{ background: #f8f9fa; border-radius: 8px; padding: 16px 24px; margin: 16px 0; }}
  .highlight {{ font-size: 1.8em; font-weight: bold; color: #e74c3c; }}
  table {{ border-collapse: collapse; width: 100%; }}
  th, td {{ border: 1px solid #ddd; padding: 8px 14px; text-align: left; }}
  th {{ background: #3498db; color: white; }}
  tr:nth-child(even) {{ background: #f2f2f2; }}
  .positive {{ color: #e74c3c; }} .negative {{ color: #27ae60; }}
  footer {{ color: #aaa; font-size: 0.85em; margin-top: 40px; border-top: 1px solid #eee; padding-top: 12px; }}
</style>
</head>
<body>
<h1>Protein-Ligand MD Simulation Report</h1>
<div class="card">
  <strong>Generated:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}<br>
  <strong>System:</strong> {params['system']['name']}<br>
  <strong>Force Field:</strong> {params['system']['protein_ff']} (protein) / {params['system']['ligand_ff']} (ligand)<br>
  <strong>Production MD:</strong> {params['md']['prod_steps'] * params['md']['dt'] / 1000:.1f} ns @ {params['md']['temp']} K
</div>

<h2>Binding Free Energy (MM-PB/GBSA)</h2>
<div class="card">
  <p class="highlight">ΔG<sub>binding</sub> = {dg.get('mean', 'N/A')} ± {dg.get('std', 'N/A')} kcal/mol</p>
</div>
<table>
  <tr><th>Energy Component</th><th>Mean (kcal/mol)</th><th>Std Dev</th></tr>
  {''.join(
    f'<tr><td>{k}</td>'
    f'<td class="{"negative" if v["mean"] < 0 else "positive"}">{v["mean"]:.2f}</td>'
    f'<td>±{v["std"]:.2f}</td></tr>'
    for k, v in mmpbsa.items()
  )}
</table>

<h2>Structural Analysis</h2>
{rmsd_img if rmsd_img else '<p><em>RMSD plots not available.</em></p>'}

<h2>Energy Decomposition</h2>
{dcomp_img if dcomp_img else '<p><em>Decomposition plot not available.</em></p>'}

<footer>
  Generated by <a href="https://github.com/YOUR_USERNAME/md-binding-template">md-binding-template</a>
  using GROMACS + gmx_MMPBSA.
</footer>
</body>
</html>"""

    REPORT.write_text(html)
    print(f"[report] HTML report saved → {REPORT}")


if __name__ == "__main__":
    generate_report()
